import { useEffect } from "react";

const docs = {
  privacy: {
    title: "Privacy Policy",
    effective: "Effective 14 April 2026",
    body: [
      ["What we collect", [
        "Contact details you give us (name, email, phone) when you book, use the contact form, or email us directly.",
        "Booking details — the service, date, and time you selected.",
        "Payment confirmation (we never see or store your card number — it is handled by the payment provider).",
        "Standard technical logs (browser type, approximate location) generated by our hosting provider.",
      ]],
      ["How we use it", [
        "To deliver the service you booked — scheduling, reminders, and the session itself.",
        "To respond to enquiries sent through the contact form.",
        "To improve the site and spot misuse.",
      ]],
      ["Who we share it with", [
        "Trusted tools that power the site (Google Calendar, EmailJS, GitHub Pages, the payment provider). Each is bound by their own terms and processes data only on our instructions.",
        "We do not sell your data. We do not share it with advertisers.",
      ]],
      ["How long we keep it", [
        "Booking records and related correspondence for up to 3 years for tax, dispute, and follow-up purposes.",
        "Contact-form messages for up to 12 months.",
      ]],
      ["Your rights", [
        "You can ask for a copy of what we hold, ask us to correct it, or ask us to delete it. Write to sauda.luzze@gmail.com.",
      ]],
    ],
  },
  terms: {
    title: "Terms of Service",
    effective: "Effective 14 April 2026",
    body: [
      ["The service", [
        "Luzze Consultancy provides advisory sessions and introductions. We are not a law firm, immigration adviser, tax adviser, or real-estate agent. Any recommendation is informational; final decisions are yours.",
      ]],
      ["Bookings and payment", [
        "Sessions must be paid for at the time of booking. Prices are in USD unless stated otherwise.",
        "The time you select is held for you only after payment clears.",
      ]],
      ["Rescheduling and cancellation", [
        "You can reschedule up to 24 hours before your slot at no cost.",
        "Cancellations more than 48 hours in advance: full refund. Inside 48 hours: we offer a credit toward a future session.",
        "No-shows are not refunded.",
      ]],
      ["Your conduct", [
        "Treat Sauda and any introduced partners with respect. We reserve the right to end a session and refund the unused portion if conduct is abusive or threatening.",
      ]],
      ["Liability", [
        "Our total liability for any claim is limited to the fee you paid for the specific session in question. We are not liable for business losses, lost profits, or indirect damages.",
      ]],
      ["Changes", [
        "We may update these terms. The version in effect when you book applies to that booking.",
      ]],
    ],
  },
  refund: {
    title: "Refund Policy",
    effective: "Effective 14 April 2026",
    body: [
      ["At a glance", [
        "Cancel more than 48 hours before your session → full refund.",
        "Cancel 24–48 hours before → credit toward a future session within 6 months.",
        "Cancel under 24 hours or no-show → no refund.",
      ]],
      ["How to request a refund", [
        "Email sauda.luzze@gmail.com with your booking details. Refunds are processed to the original payment method within 10 business days.",
      ]],
      ["If we need to reschedule", [
        "If Luzze has to cancel a session for any reason, you get a full refund or the option to rebook at no extra cost — your choice.",
      ]],
      ["Exceptional circumstances", [
        "If you miss a session because of a genuine emergency (illness, bereavement, travel disruption), get in touch — we handle these case by case and usually offer a reschedule.",
      ]],
    ],
  },
};

export default function LegalModal({ doc, onClose }) {
  useEffect(() => {
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const onKey = (e) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => {
      document.body.style.overflow = prev;
      window.removeEventListener("keydown", onKey);
    };
  }, [onClose]);

  if (!doc || !docs[doc]) return null;
  const { title, effective, body } = docs[doc];

  return (
    <div
      onClick={onClose}
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(30,40,48,0.75)",
        zIndex: 210,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "32px 12px",
        overflowY: "auto",
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
        aria-labelledby="luzze-legal-title"
        style={{
          background: "#fff",
          color: "#4A5C6A",
          maxWidth: 680,
          width: "100%",
          borderRadius: 6,
          padding: "clamp(24px, 4vw, 40px)",
          boxShadow: "0 30px 80px rgba(0,0,0,0.4)",
          position: "relative",
          fontFamily: "'DM Sans', sans-serif",
          margin: "auto",
        }}
      >
        <button
          onClick={onClose}
          style={{
            position: "absolute",
            top: 16,
            right: 16,
            background: "transparent",
            border: "none",
            fontSize: 22,
            cursor: "pointer",
            color: "rgba(74,92,106,0.6)",
            lineHeight: 1,
          }}
          aria-label="Close"
        >
          ×
        </button>
        <h2
          id="luzze-legal-title"
          style={{
            fontFamily: "'Playfair Display', serif",
            fontWeight: 400,
            fontSize: "clamp(22px, 4vw, 30px)",
            margin: "0 0 4px",
            paddingRight: 24,
          }}
        >
          {title}
        </h2>
        <div
          style={{
            fontSize: 11,
            letterSpacing: 2,
            textTransform: "uppercase",
            color: "#3EA8C8",
            marginBottom: 24,
            fontWeight: 600,
          }}
        >
          {effective}
        </div>
        {body.map(([heading, bullets], i) => (
          <div key={i} style={{ marginBottom: 24 }}>
            <h3
              style={{
                fontFamily: "'Playfair Display', serif",
                fontSize: 18,
                fontWeight: 400,
                margin: "0 0 8px",
              }}
            >
              {heading}
            </h3>
            <ul
              style={{
                margin: 0,
                paddingLeft: 20,
                fontSize: 14,
                lineHeight: 1.7,
                color: "#6b7c8a",
              }}
            >
              {bullets.map((b, j) => (
                <li key={j} style={{ marginBottom: 6 }}>{b}</li>
              ))}
            </ul>
          </div>
        ))}
        <div style={{ fontSize: 12, color: "rgba(74,92,106,0.6)", marginTop: 16 }}>
          Questions? Email{" "}
          <a href="mailto:sauda.luzze@gmail.com" style={{ color: "#3EA8C8" }}>
            sauda.luzze@gmail.com
          </a>
          .
        </div>
      </div>
    </div>
  );
}
